## Installation

In [2]:
import torch
print(f"PyTorch Version: {torch.__version__}")

PyTorch Version: 2.6.0+cu124


In [3]:
# Check if CUDA (GPU support) is available
cuda_available = torch.cuda.is_available()
print(f"CUDA Available: {cuda_available}")
if cuda_available:
    # Get the number of GPUs available
    print(f"Number of GPUs: {torch.cuda.device_count()}")
    # Get the name of the current GPU
    print(f"Current GPU Name: {torch.cuda.get_device_name(torch.cuda.current_device())}")
else:
    print("PyTorch is using CPU.")

CUDA Available: True
Number of GPUs: 2
Current GPU Name: Tesla T4


## Tensors

#### Tensor from Python list

In [1]:
import torch
import numpy as np

#create a tensor from a python list
data_list = [[1,2], [3,4]]
tensor_from_list = torch.tensor(data_list)

print(tensor_from_list)

tensor([[1, 2],
        [3, 4]])


In [3]:
print(f"data type: {tensor_from_list.dtype}")
print(f"shape: {tensor_from_list.shape}")

data type: torch.int64
shape: torch.Size([2, 2])


#### Tensor from Numpy array

In [4]:
data_numpy = np.array([[5.0, 6.0], [7.0, 8.0]])
tensor_from_numpy = torch.tensor(data_numpy)

In [5]:
print(f"Data type: {tensor_from_numpy.dtype}")
print(f"Shape: {tensor_from_numpy.shape}")

Data type: torch.float64
Shape: torch.Size([2, 2])


#### Creating Tensors with Specific Shapes and Values

In [7]:
# define the sesired shape
shape = (2, 3) # 2 rows, 3 columns

zeros_tensor = torch.zeros(shape)
ones_tensor = torch.ones(shape)
empty_tensor = torch.empty(shape)

print(f"\nZeros Tensor (shape {shape}):")
print(zeros_tensor)

print(f"\nOnes Tensor (shape {shape}):")
print(ones_tensor)

print(f"\nEmpty Tensor (shape {shape}):")
print(empty_tensor)


Zeros Tensor (shape (2, 3)):
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones Tensor (shape (2, 3)):
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Empty Tensor (shape (2, 3)):
tensor([[0.0000e+00, 0.0000e+00, 1.1210e-44],
        [1.1210e-44, 0.0000e+00, 5.7453e-44]])


In [8]:
# create a tensor of ones with integer type
onesinttensor = torch.ones(shape, dtype=torch.int32)
print(onesinttensor)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [10]:
#tensors with random values

rand_tensor = torch.rand(shape) #uniform distribution
randn_tensor = torch.randn(shape) #standard normal distribution

print(f"\nRandom Tensor (Uniform [0, 1), shape {shape}):")
print(rand_tensor)

print(f"\nRandom Tensor (Standard Normal, shape {shape}):")
print(randn_tensor)


Random Tensor (Uniform [0, 1), shape (2, 3)):
tensor([[0.6446, 0.6244, 0.4380],
        [0.3308, 0.7796, 0.7324]])

Random Tensor (Standard Normal, shape (2, 3)):
tensor([[ 0.0957,  0.9816,  0.1816],
        [-0.0825, -0.4397,  1.3644]])


In [11]:
#creating tensors based on other tensors

# Use an existing tensor as a template
base_tensor = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
print(f"\nBase Tensor (shape {base_tensor.shape}, dtype {base_tensor.dtype}):")
print(base_tensor)

# create tensors matching the base tensor's properties
zeros_like_base = torch.zeros_like(base_tensor)
rand_like_base = torch.rand_like(base_tensor)

print("\nZeros tensor like base:")
print(zeros_like_base)
print(f"Shape: {zeros_like_base.shape}, dtype: {zeros_like_base.dtype}")

print("\nRandom tensor like base:")
print(rand_like_base)
print(f"Shape: {rand_like_base.shape}, dtype: {rand_like_base.dtype}")

# These functions take an existing tensor as input and return a new tensor with 
# the specified content (zeros, ones, random) but matching the input tensor's shape 
# and dtype, unless explicitly overridden.


Base Tensor (shape torch.Size([2, 2]), dtype torch.float32):
tensor([[1., 2.],
        [3., 4.]])

Zeros tensor like base:
tensor([[0., 0.],
        [0., 0.]])
Shape: torch.Size([2, 2]), dtype: torch.float32

Random tensor like base:
tensor([[0.9321, 0.8441],
        [0.9062, 0.4007]])
Shape: torch.Size([2, 2]), dtype: torch.float32


### Basic Tensor Operations

In [1]:
import torch

# Create two tensors
a = torch.tensor([[1., 2.], [3., 4.]])
b = torch.tensor([[5., 6.], [7., 8.]])

# Addition
sum_tensor = a + b
print("Addition (a + b):\n", sum_tensor)
print("Addition (torch.add(a, b)):\n", torch.add(a, b))

Addition (a + b):
 tensor([[ 6.,  8.],
        [10., 12.]])
Addition (torch.add(a, b)):
 tensor([[ 6.,  8.],
        [10., 12.]])


In [3]:
# Subtraction
diff_tensor = a - b
print("\nSubtraction (a - b):\n", diff_tensor)
print("Subtraction (torch.sub(a, b)):\n", torch.sub(a, b))


Subtraction (a - b):
 tensor([[-4., -4.],
        [-4., -4.]])
Subtraction (torch.sub(a, b)):
 tensor([[-4., -4.],
        [-4., -4.]])


In [4]:
# Element-wise Multiplication
mul_tensor = a * b
print("\nElement-wise Multiplication (a * b):\n", mul_tensor)
print("Element-wise Multiplication (torch.mul(a, b)):\n", torch.mul(a, b))


Element-wise Multiplication (a * b):
 tensor([[ 5., 12.],
        [21., 32.]])
Element-wise Multiplication (torch.mul(a, b)):
 tensor([[ 5., 12.],
        [21., 32.]])


In [5]:
# Division
div_tensor = a / b
print("\nDivision (a / b):\n", div_tensor)

# Exponentiation
pow_tensor = a ** 2
print("\nExponentiation (a ** 2):\n", pow_tensor)
print("Exponentiation (torch.pow(a, 2)):\n", torch.pow(a, 2))


Division (a / b):
 tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

Exponentiation (a ** 2):
 tensor([[ 1.,  4.],
        [ 9., 16.]])
Exponentiation (torch.pow(a, 2)):
 tensor([[ 1.,  4.],
        [ 9., 16.]])


#### In-place Operations
In-place functions are usually identifiable by a trailing underscore _ in their name (e.g., add_, mul_).

In [6]:
a = torch.tensor([[1., 2.], [3., 4.]])
b = torch.tensor([[5., 6.], [7., 8.]])

# a = a + b # Standard addition creates a new tensor
print("Original tensor 'a':\n", a)
# Perform in-place addition
a.add_(b) # a is modified directly
print("\nTensor 'a' after a.add_(b):\n", a)


Original tensor 'a':
 tensor([[1., 2.],
        [3., 4.]])

Tensor 'a' after a.add_(b):
 tensor([[ 6.,  8.],
        [10., 12.]])


In [7]:
# Another in-place operation
a.mul_(2) # Multiply 'a' by 2 in-place
print("\nTensor 'a' after a.mul_(2):\n", a)


Tensor 'a' after a.mul_(2):
 tensor([[12., 16.],
        [20., 24.]])


#### Scalar Operations

In [8]:
t = torch.tensor([[1, 2, 3], [4, 5, 6]])
scalar = 10

In [9]:
# Add scalar
print("t + scalar:\n", t + scalar)

# Multiply by scalar
print("\nt * scalar:\n", t * scalar)

# Subtract scalar
print("\nt - scalar:\n", t - scalar)

t + scalar:
 tensor([[11, 12, 13],
        [14, 15, 16]])

t * scalar:
 tensor([[10, 20, 30],
        [40, 50, 60]])

t - scalar:
 tensor([[-9, -8, -7],
        [-6, -5, -4]])


In [10]:
# other mathematical functions

t = torch.tensor([[1., 4.], [9., 16.]])
# Square root
print("Square Root (torch.sqrt(t)):\n", torch.sqrt(t))

# Exponential
print("\nExponential (torch.exp(t)):\n", torch.exp(t)) # e^x

Square Root (torch.sqrt(t)):
 tensor([[1., 2.],
        [3., 4.]])

Exponential (torch.exp(t)):
 tensor([[2.7183e+00, 5.4598e+01],
        [8.1031e+03, 8.8861e+06]])


In [11]:
# Natural Logarithm
# Note: Ensure values are positive for log
t_pos = torch.abs(t) + 1e-6 # Add small epsilon for stability if zeros exist
print("\nNatural Log (torch.log(t_pos)):\n", torch.log(t_pos))

# Absolute value
t_neg = torch.tensor([[-1., 2.], [-3., 4.]])
print("\nAbsolute Value (torch.abs(t_neg)):\n", torch.abs(t_neg))


Natural Log (torch.log(t_pos)):
 tensor([[9.5367e-07, 1.3863e+00],
        [2.1972e+00, 2.7726e+00]])

Absolute Value (torch.abs(t_neg)):
 tensor([[1., 2.],
        [3., 4.]])


Many other functions like `torch.sin(), torch.cos(), torch.tanh(), torch.sigmoid()` are available in the torch module.

#### Reduction Operations
reduce the number of elements in a tensor

In [12]:
import torch

t = torch.tensor([[1., 2., 3.], [4., 5., 6.]])
print("Original Tensor:\n", t)

# Sum of all elements
total_sum = torch.sum(t)
print("\nSum of all elements (torch.sum(t)):", total_sum)

Original Tensor:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])

Sum of all elements (torch.sum(t)): tensor(21.)


In [13]:
# Mean of all elements
# Note: Requires float tensor for mean calculation
mean_val = torch.mean(t.float())
print("Mean of all elements (torch.mean(t.float())):", mean_val)

Mean of all elements (torch.mean(t.float())): tensor(3.5000)


In [14]:
# Max value
max_val = torch.max(t)
print("Max value in tensor (torch.max(t)):", max_val)

# Min value
min_val = torch.min(t)
print("Min value in tensor (torch.min(t)):", min_val)

Max value in tensor (torch.max(t)): tensor(6.)
Min value in tensor (torch.min(t)): tensor(1.)


In [15]:
import torch

t = torch.tensor([[1., 2., 3.], [4., 5., 6.]])
print("Original Tensor:\n", t)

# Sum along dimension 0 (summing rows)
sum_dim0 = torch.sum(t, dim=0)
print("\nSum along dim=0 (columns):\n", sum_dim0)
# Summing the tensor [[1, 2, 3], [4, 5, 6]] along dim=1 results in [1+2+3, 4+5+6] = [6, 15].

# Sum along dimension 1 (summing columns)
sum_dim1 = torch.sum(t, dim=1)
print("\nSum along dim=1 (rows):\n", sum_dim1)

# Mean along dimension 1
mean_dim1 = torch.mean(t.float(), dim=1)
print("\nMean along dim=1 (rows):\n", mean_dim1)

Original Tensor:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])

Sum along dim=0 (columns):
 tensor([5., 7., 9.])

Sum along dim=1 (rows):
 tensor([ 6., 15.])

Mean along dim=1 (rows):
 tensor([2., 5.])


In [16]:
# You can compare tensors element-wise using standard comparison operators (>, <, >=, <=, ==, !=). 
# The result is a tensor of boolean values (torch.bool).

a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[1, 5], [0, 4]])

print("Tensor 'a':\n", a)
print("Tensor 'b':\n", b)

# Equality check
print("\na == b:\n", a == b)

# Greater than check
print("\na > b:\n", a > b)

# Less than or equal check
print("\na <= b:\n", a <= b)

Tensor 'a':
 tensor([[1, 2],
        [3, 4]])
Tensor 'b':
 tensor([[1, 5],
        [0, 4]])

a == b:
 tensor([[ True, False],
        [False,  True]])

a > b:
 tensor([[False, False],
        [ True, False]])

a <= b:
 tensor([[ True,  True],
        [False,  True]])


Logical operations (torch.logical_and(), torch.logical_or(), torch.logical_not()) operate element-wise on boolean tensors or tensors that can be evaluated in a boolean context (where 0 is false and non-zero is true).

In [17]:
bool_a = torch.tensor([[True, False], [True, True]])
bool_b = torch.tensor([[False, True], [True, False]])

print("Boolean Tensor 'bool_a':\n", bool_a)
print("Boolean Tensor 'bool_b':\n", bool_b)

Boolean Tensor 'bool_a':
 tensor([[ True, False],
        [ True,  True]])
Boolean Tensor 'bool_b':
 tensor([[False,  True],
        [ True, False]])


In [18]:
# Logical AND
print("\ntorch.logical_and(bool_a, bool_b):\n", torch.logical_and(bool_a, bool_b))


torch.logical_and(bool_a, bool_b):
 tensor([[False, False],
        [ True, False]])


In [19]:
# Logical OR
print("\ntorch.logical_or(bool_a, bool_b):\n", torch.logical_or(bool_a, bool_b))


torch.logical_or(bool_a, bool_b):
 tensor([[True, True],
        [True, True]])


In [20]:
# Logical NOT
print("\ntorch.logical_not(bool_a):\n", torch.logical_not(bool_a))


torch.logical_not(bool_a):
 tensor([[False,  True],
        [False, False]])


### Relationship with NumPy
PyTorch Tensors are very similar to NumPy arrays: both are abstractions for multi-dimensional grids of numbers.

In [21]:
import numpy as np
import torch

# Create a NumPy array
numpy_array = np.array([[1, 2], [3, 4]], dtype=np.float32)
print(f"NumPy array:\n{numpy_array}")
print(f"NumPy array type: {numpy_array.dtype}")

NumPy array:
[[1. 2.]
 [3. 4.]]
NumPy array type: float32


In [22]:
# Convert NumPy array to PyTorch Tensor
pytorch_tensor = torch.from_numpy(numpy_array)
print(f"\nPyTorch Tensor:\n{pytorch_tensor}")
print(f"PyTorch Tensor type: {pytorch_tensor.dtype}")


PyTorch Tensor:
tensor([[1., 2.],
        [3., 4.]])
PyTorch Tensor type: torch.float32


When using torch.from_numpy(), the resulting PyTorch Tensor and the original NumPy array share the same underlying memory location on the CPU. This means that modifying one object will affect the other. 

In [23]:
# Modify the NumPy array
numpy_array[0, 0] = 99
print(f"\nModified NumPy array:\n{numpy_array}")
print(f"PyTorch Tensor after modifying NumPy array:\n{pytorch_tensor}")



Modified NumPy array:
[[99.  2.]
 [ 3.  4.]]
PyTorch Tensor after modifying NumPy array:
tensor([[99.,  2.],
        [ 3.,  4.]])


In [24]:
# Modify the PyTorch Tensor
pytorch_tensor[1, 1] = -1
print(f"\nModified PyTorch Tensor:\n{pytorch_tensor}")
print(f"NumPy array after modifying PyTorch Tensor:\n{numpy_array}")


Modified PyTorch Tensor:
tensor([[99.,  2.],
        [ 3., -1.]])
NumPy array after modifying PyTorch Tensor:
[[99.  2.]
 [ 3. -1.]]


changes are reflected in both objects because they point to the same data in memory.

In [25]:
# PyTorch Tensor to NumPy Array
# Create a PyTorch Tensor on the CPU
cpu_tensor = torch.tensor([[10.0, 20.0], [30.0, 40.0]])
print(f"Original PyTorch Tensor (CPU):\n{cpu_tensor}")

# Convert Tensor to NumPy array
numpy_array_converted = cpu_tensor.numpy()
print(f"\nConverted NumPy array:\n{numpy_array_converted}")
print(f"NumPy array type: {numpy_array_converted.dtype}")

Original PyTorch Tensor (CPU):
tensor([[10., 20.],
        [30., 40.]])

Converted NumPy array:
[[10. 20.]
 [30. 40.]]
NumPy array type: float32


In [26]:
# Modify the Tensor
cpu_tensor[0, 1] = 25.0
print(f"\nModified PyTorch Tensor:\n{cpu_tensor}")
print(f"NumPy array after modifying Tensor:\n{numpy_array_converted}")

# Modify the NumPy array
numpy_array_converted[1, 0] = 35.0
print(f"\nModified NumPy array:\n{numpy_array_converted}")
print(f"Tensor after modifying NumPy array:\n{cpu_tensor}")


Modified PyTorch Tensor:
tensor([[10., 25.],
        [30., 40.]])
NumPy array after modifying Tensor:
[[10. 25.]
 [30. 40.]]

Modified NumPy array:
[[10. 25.]
 [35. 40.]]
Tensor after modifying NumPy array:
tensor([[10., 25.],
        [35., 40.]])


The .numpy() method only works for Tensors stored on the CPU. If your Tensor is on a GPU, you must first move it to the CPU using the .cpu() method before converting it to a NumPy array. Attempting to call .numpy() directly on a GPU Tensor will result in an error.

In [27]:
# Example assuming a GPU is available
if torch.cuda.is_available():
    gpu_tensor = torch.tensor([[1.0, 2.0], [3.0, 4.0]], device='cuda')
    print(f"\nTensor on GPU:\n{gpu_tensor}")

    # This would cause an error: numpy_from_gpu = gpu_tensor.numpy()

    # Correct way: move to CPU first
    cpu_tensor_from_gpu = gpu_tensor.cpu()
    numpy_from_gpu = cpu_tensor_from_gpu.numpy()
    print(f"\nConverted NumPy array (from GPU Tensor):\n{numpy_from_gpu}")

    # Note: numpy_from_gpu shares memory with cpu_tensor_from_gpu,
    # but NOT with the original gpu_tensor.
else:
    print("\nCUDA not available, skipping GPU to NumPy example.")



Tensor on GPU:
tensor([[1., 2.],
        [3., 4.]], device='cuda:0')

Converted NumPy array (from GPU Tensor):
[[1. 2.]
 [3. 4.]]
